[package]
name = "lgtv"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "lgtv"
path = "main.rs"

[dependencies]
lg-webos-client = { git = "https://github.com/xDarksome/lg-webos-client" }
structopt = "0.3"
tokio = { version = "1.11.0", features = ["full"] }

